name: Register Game via Browser

on:
  workflow_dispatch:
    inputs:
      game_name:
        description: 'Nama game'
        required: true
      zip_url:
        description: 'URL ZIP file (misal dari Firebase Storage)'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y unzip curl

      - name: Download ZIP
        run: |
          curl -L ${{ github.event.inputs.zip_url }} -o game.zip

      - name: Create folder and extract
        run: |
          FOLDER_NAME=$(echo "${{ github.event.inputs.game_name }}" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9' '_')
          mkdir -p "$FOLDER_NAME"
          unzip -o game.zip -d "$FOLDER_NAME"

      - name: Commit & Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add game ${{ github.event.inputs.game_name }}"
          git push
